[?1049h[22;0;0t[>4;2m[?1h=[?2004h[?1004h[1;58r[?12h[?12l[22;2t[22;1t[27m[23m[29m[m[H[2J[?25l[58;1H"/tmp/kubectl-edit-1925305775.yaml" 71L, 2496B[1;1H[34m# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#[m
[36mapiVersion[m[35m:[m apps/v1
[36mkind[m[35m:[m Deployment
[36mmetadata[m[35m:[m
  [36mannotations[m[35m:[m
    [36mdeployment.kubernetes.io/revision[m[35m:[m [31m"5"[m
    [36mkubectl.kubernetes.io/last-applied-configuration[m[35m:[m |[11;7H[35m{[m[31m"apiVersion"[m[35m:[m[31m"apps/v1"[m,[31m"kind"[m[35m:[m[31m"Deployment"[m,[31m"metadata"[m[35m:{[m[31m"annotations"[m[35m:{}[m,[31m"creationTimestamp"[m[35m:[m[31mnull[m,[31m"labels"[m[35m:{[m[31m"app"[m[35m:[m[31m"irohide-pod-deployement"[m[35m}[m,[31m"name"[m[35m:[m[31m"irohide-pod-deployee[12;1Hment"[m,[31m"namespace"[m[35m:[m[31m"default"[m[35m}[m,[31m"spec"[m[35m:{[m[31m"replicas"[m[35m:[m2,[31m"selector"[m[35m:{[m[31m"matchLabels"[m[35m:{[m[31m"app"[m[35m:[m[31m"irohide-pod-deployement"[m[35m}}[m,[31m"strategy"[m[35m:{}[m,[31m"template"[m[35m:{[m[31m"metadata"[m[35m:{[m[31m"creationTimestamp"[m[35m:[m[31mnull[m,,[13;1H[31m"labels"[m[35m:{[m[31m"app"[m[35m:[m[31m"irohide-pod-deployement"[m[35m}}[m,[31m"spec"[m[35m:{[m[31m"containers"[m[35m:[{[m[31m"image"[m[35m:[m[31m"nginx"[m,[31m"name"[m[35m:[m[31m"nginx"[m,[31m"ports"[m[35m:[{[m[31m"containerPort"[m[35m:[m80[35m}][m,[31m"resources"[m[35m:{}}]}}}[m,[31m"status"[m[35m:{}}[m
  [36mcreationTimestamp[m[35m:[m [31m"2025-05-08T09:17:48Z"[m
  [36mgeneration[m[35m:[m [31m6[m
  [36mlabels[m[35m:[m
    [36mapp[m[35m:[m irohide-pod-deployement
  [36mname[m[35m:[m irohide-pod-deployement
  [36mnamespace[m[35m:[m default
  [36mresourceVersion[m[35m:[m [31m"19060"[m
  [36muid[m[35m:[m 0a7577f6-9460-4e4e-87e9-59556e0d6ab3
[36mspec[m[35m:[m
  [36mprogressDeadlineSeconds[m[35m:[m [31m600[m
  [36mreplicas[m[35m:[m [31m4[m
  [36mrevisionHistoryLimit[m[35m:[m [31m10[m
  [36mselector[m[35m:[m
    [36mmatchLabels[m[35m:[m[28;7H[36mapp[m[35m:[m irohide-pod-deployement
  [36mstrategy[m[35m:[m
    [36mrollingUpdate[m[35m:[m[31;7H[36mmaxSurge[m[35m:[m 25%[32;7H[36mmaxUnavailable[m[35m:[m 25%
    [36mtype[m[35m:[m RollingUpdate
  [36mtemplate[m[35m:[m
    [36mmetadata[m[35m:[m[36;7H[36mcreationTimestamp[m[35m:[m [31mnull[m[37;7H[36mlabels[m[35m:[m[38;9H[36mapp[m[35m:[m irohide-pod-deployement
    [36mspec[m[35m:[m[40;7H[36mcontainers[m[35m:[m[41;7H[33m- [m[36mimage[m[35m:[m nginx[42;9H[36mimagePullPolicy[m[35m:[m Always[43;9H[36mname[m[35m:[m nginx[44;9H[36mports[m[35m:[m[45;9H[33m- [m[36mcontainerPort[m[35m:[m [31m80[m[46;11H[36mprotocol[m[35m:[m TCP[47;9H[36mresources[m[35m:[m [35m{}[m[48;9H[36mterminationMessagePath[m[35m:[m /dev/termination-log[49;9H[36mterminationMessagePolicy[m[35m:[m File[50;7H[36mdnsPolicy[m[35m:[m ClusterFirst[51;7H[36mrestartPolicy[m[35m:[m Always[52;7H[36mschedulerName[m[35m:[m default-scheduler[53;7H[36msecurityContext[m[35m:[m [35m{}[m[54;7H[36mterminationGracePeriodSeconds[m[35m:[m [31m30[m
[36mstatus[m[35m:[m
  [36mavailableReplicas[m[35m:[m [31m4[m
  [36mconditions[m[35m:[m[58;157H1,1[11CTop[1;1H[?25h[?4m[58;1H[?2004l[>4;m[23;2t[23;1t[58;1H[K[58;1H[?1004l[?2004l[?1l>[?1049l[23;0;0t[>4;m