apiVersion: v1
kind: PersistentVolume
metadata:
  name: energon-persistent-volume
spec:
  capacity:
    storage: 10Gi #this is an thin provisioing 
  volumeMode: Filesystem #it will look for the particular file system
  accessModes:
    - ReadWriteOnce #readwritemany #read 
  storageClassName: energonpersistentvolume
  hostPath:
    path: "/mnt/Energon" #this is the path where the data will be stored

